channels/src/cfehome/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html")),
    path('admin/', admin.site.urls),
    path('messages/', include('chat.urls')),
]

channels/src/chat/urls.py
from django.urls import path, re_path


from .views import ThreadView, InboxView

app_name = 'chat'
urlpatterns = [
    path("", InboxView.as_view()),
    re_path(r"^(?P<username>[\w.@+-]+)", ThreadView.as_view()),
]

channels/src/chat/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username):
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                    first=user,
                    second=user2
                )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    first = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ThreadManager()


class ChatMessage(models.Model):
    thread = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

channels/src/chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

channels/src/chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.views.generic.edit import FormMixin
from django.views.generic import DetailView, ListView

from .forms import ComposeForm
from .models import Thread, ChatMessage


class InboxView(LoginRequiredMixin, ListView):
    template_name = 'chat/inbox.html'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)


class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/thread.html'
    form_class = ComposeForm
    success_url = './'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username = self.kwargs.get("username")
        obj, created = Thread.objects.get_or_new(self.request.user, other_username)
        if obj is None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get('message')
        ChatMessage.objects.create(user=user, thread=thread, message=message)

        return super().form_valid(form)

channels/src/chat/templates/chat/inbox.html
{% extends "base.html" %}

{% block content %}


{% endblock %}

channels/src/chat/templates/chat/thread.html
{% extends "base.html" %}

{% block content %}
<h3>Thread for {% if user != object.first %}{{ object.first }}{% else %}{{ object.second }}{% endif %}</h3>

<ul>
    {% for chat in object.chatmessage_set.all %}

    <li>{{ chat.message }} via {{ chat.user }}</li>

    {% endfor %}
</ul>

<form id='form' method='POST'> {% csrf_token %}
    {{form.as_p }}
    <input type='submit' class='btn btn-primary'/>
</form>
{% endblock %}

{% block script %}

<script>
    $(document).ready(function () {
        const loc = window.location;
        let wsStart = "ws://";
        if (loc.protocol === "https:") {
            wsStart = "wss://"
        }
        let webSocketEndpoint = wsStart + loc.host + '/chat/';  // ws : wss
        let socket = new WebSocket(webSocketEndpoint);

        let formData = $("#form");
        let messageInput = $("#id_message");

        socket.onmessage = function (e) {
            console.log('message', e);
            console.log(e.data);
        };

        socket.onopen = function (e) {
            console.log('open', e);
            formData.submit(function (event) {
                event.preventDefault();
                let messageText = messageInput.val();
                let jsonData = JSON.stringify({msg: messageText, user:'admin'});
                socket.send(jsonData);
            });
        };

        socket.onerror = function (e) {
            console.log('error', e)
        };

        socket.onclose = function (e) {
            console.log('closed', e)
        };

        if (socket.readyState === WebSocket.OPEN) {

        } else if (socket.readyState === WebSocket.CONNECTING){
            console.log("connecting..")
        }
    })
</script>
{% endblock %}